### ISSUE TITLE
Errors appear during running the classes using the jar file of jrosbridge.

### ISSUE THREAD

**Issue by paive** [rctoris/jrosbridge#17]
I use ant to compile the source code of jrosbridge, and get the jar file. Then i compile the code in the "REDAME.md" using the above jar file and there is no errors. However when i run the classes, the follow errors appears, the problems occurs in the method ros.connect(), can anyone tell me the reason and the solution.

> [java] Exception in thread "main" java.lang.RuntimeException: Could not find an implementation class.
>      [java]   at javax.websocket.ContainerProvider.getWebSocketContainer(ContainerProvider.java:73)
>      [java]   at edu.wpi.rail.jrosbridge.Ros.connect(Unknown Source)
>      [java]   at DemoJROSB.main(Unknown Source)
>      [java] Java Result: 1

**Comment by rctoris** [comment]
This code is based on JavaEE which defines a certain API level definition for things like websockets. In addition to `jrosbridge`, you will also need an implementation-level JAR of anything `jrosbridge` uses. This is what Maven is built to handle. It will download and use any listed dependencies for you (https://github.com/rctoris/jrosbridge/blob/develop/pom.xml#L39-L67). If you want to build this package from source, you will need to use Maven to build it. To build, you can run the following:

`mvn install -DskipTests=true`

It is easier to develop your project as its own Maven project and list `jrosbridge` as a dependency directly. 

```
<dependency>
    <groupId>edu.wpi.rail</groupId>
    <artifactId>jrosbridge</artifactId>
    <version>0.2.0</version>
</dependency>
```

**Comment by paive** [comment]
Thanks for your advice. The problem has been solved in another way, i use ant to compile and run the code in the whole progress(because of not being familiar with maven -_-!! ). Lacking the jar file

> tyrus-standalone-client-1.9.jar

 caused the problem. After adding the proper jar file, i succeed running the code.

**Comment by paive** [comment]
@rctoris Thanks for your advice. The problem has been solved in another way, i use ant to compile and run the code in the whole progress(because of not being familiar with maven -_-!! ). Lacking the jar file

> tyrus-standalone-client-1.9.jar

 caused the problem. After adding the proper jar file, i succeed running the code.
