### ISSUE TITLE
cant publish std_msgs/String

### ISSUE THREAD

**Issue by AviKenz** [rctoris/jrosbridge#29]
im getting:

`[INFO] [rosbridge_websocket]: Client disconnected. 0 clients total.`
`[INFO] [rosbridge_websocket]: Client connected. 1 clients total.`
`[ERROR] [rosbridge_websocket]: [Client 1] [id: advertise:/my_publisher:0] advertise: std_msgs/String is not a valid type string`

im using exactly the same code from the [readme page](https://github.com/rctoris/jrosbridge):

`Ros ros = new Ros("localhost");`
`	ros.connect();`
`	Topic echo = new Topic(ros, "/echo", "std_msgs/String");`
`	Message toSend = new Message("{\"data\": \"hello, world!\"}");`
`	echo.publish(toSend);`

**My Configuration:**
ROS: ros-dashing
Client Lib: from [Here](https://github.com/rctoris/jrosbridge/issues/19#issuecomment-295778828) (im running Client lib on an Android device)

**Comment by travipross** [comment]
Try changing `std_msgs/String` to `std_msgs/msg/String`.

For reference:
- [this is the old Melodic spec](http://docs.ros.org/melodic/api/std_msgs/html/msg/String.html)
- [This is the definition in Eloquent](https://github.com/ros2/common_interfaces/blob/eloquent/std_msgs/msg/String.msg)

**Comment by AviKenz** [comment]
it works ! thanks a lot.😀
